// <auto-generated />
namespace ValidataTestWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class m80 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m80));
        
        string IMigrationMetadata.Id
        {
            get { return "202204211202192_m80"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
