// <auto-generated />
namespace ValidataTestWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class m61 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m61));
        
        string IMigrationMetadata.Id
        {
            get { return "202204082146346_m61"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
